#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts hosts.new
sudo sed -i 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts
sudo sh -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'

